<?php
require __DIR__.'/includes/bootstrap.php';require __DIR__.'/includes/components.php';
$city=(string)($_GET['city']??'Jaipur');$allowed=wz_data('cities');if(!in_array($city,$allowed,true))$city='Jaipur';
$heroMap=['Jaipur'=>'https://images.unsplash.com/photo-1767158597961-bd58dccc16bd?auto=format&fit=crop&w=1900&q=92','Udaipur'=>'https://images.unsplash.com/photo-1770665567877-72ee8a7c9051?auto=format&fit=crop&w=1900&q=92','Goa'=>'https://images.unsplash.com/photo-1710952356679-1eff1cb5ba64?auto=format&fit=crop&w=1900&q=92','Delhi NCR'=>'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1900&q=92','Mumbai'=>'https://images.unsplash.com/photo-1751608734207-1c68d53554b4?auto=format&fit=crop&w=1900&q=92'];$hero=$heroMap[$city]??'https://images.unsplash.com/photo-1587271636175-90d58cdad458?auto=format&fit=crop&w=1900&q=92';
$pageTitle=$city.' Event Guide';$pageDescription='Discover venues, vendors, ideas and planning inspiration for celebrations in '.$city.'.';$pageKey='city';
$localVendors=array_values(array_filter(wz_data('vendors'),fn($v)=>($v['city']??'')===$city));$localWeddings=array_values(array_filter(wz_data('weddings'),fn($w)=>($w['city']??'')===$city));
require __DIR__.'/includes/header.php';?>
<main><section class="city-hero"><div class="city-hero-bg"><img src="<?=h($hero)?>" alt="<?=h($city)?> event destination"></div><div class="container city-hero-inner reveal"><span class="eyebrow light">WEDDING ZA CITY EDIT</span><h1><?=h($city)?></h1><p>A considered starting point for venue hunting, vendor discovery and the details that make any celebration in <?=h($city)?> actually work.</p><div class="city-facts"><div><strong><?=max(count($localVendors),4)?>+</strong><span>vendor picks</span></div><div><strong><?=count($localWeddings)?:'Fresh'?></strong><span>real celebration stories</span></div><div><strong>1</strong><span>focused shortlist</span></div></div></div></section>
<section class="section"><div class="container city-guide"><div class="city-guide-media reveal"><img data-parallax=".03" src="<?=h($hero)?>" alt="<?=h($city)?> celebration"></div><div class="city-guide-copy reveal delay-1"><span class="eyebrow">BEFORE YOU BOOK ANYTHING</span><h2>Plan the city,<br>then the event.</h2><p>The venue inventory, transport, season, guest movement and local vendor network influence nearly every other decision. Use this guide as the practical layer behind the pretty pictures.</p><div class="guide-list"><div><b>01</b><span><strong>Lock the guest logic first</strong><span>Local vs destination guests changes rooming, transport and your realistic venue list.</span></span></div><div><b>02</b><span><strong>Compare spaces by function</strong><span>Think arrival, main function, dining, performance and guest flow — not just one hero space.</span></span></div><div><b>03</b><span><strong>Shortlist local specialists</strong><span>Photography, planning, decor, food and hospitality teams with local familiarity reduce friction.</span></span></div></div></div></div></section>
<section class="section paper-2"><div class="container"><div class="section-head"><div><span class="eyebrow">THE <?=h(strtoupper($city))?> EDIT</span><h2>Vendors to open<br>first.</h2></div><a class="text-link" href="vendors.php?city=<?=urlencode($city)?>">See all <?=h($city)?> vendors ↗</a></div><div class="vendor-grid"><?php $display=$localVendors?:array_slice(wz_data('vendors'),0,6);foreach(array_slice($display,0,6) as $v)wz_vendor_card($v);?></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">START BY CATEGORY</span><h2>Your event team,<br>one decision at a time.</h2></div></div><div class="category-scroller"><?php foreach(array_slice(wz_data('categories'),0,4) as $c):?><a class="category-luxe" href="vendors.php?city=<?=urlencode($city)?>&category=<?=urlencode($c['name'])?>"><img src="<?=h($c['image'])?>" alt="<?=h($c['name'])?>"><div class="category-luxe-copy"><small><?=h($city)?></small><h3><?=h($c['name'])?></h3><p><?=h($c['sub'])?></p><b>Browse ↗</b></div></a><?php endforeach;?></div></div></section>
</main><?php require __DIR__.'/includes/footer.php';?>
