<?php
require __DIR__.'/includes/bootstrap.php';require __DIR__.'/includes/components.php';
$id=(string)($_GET['id']??'amber-courtyard');$v=wz_vendor($id)??(wz_data('vendors')[0]??null);if(!$v){http_response_code(404);header('Location:404.php');exit;}
$pageTitle=$v['name'];$pageDescription=$v['about'];$pageKey='vendor';require __DIR__.'/includes/header.php';
$images=$v['images']??[$v['image']];while(count($images)<3)$images[]=$v['image'];
?>
<main>
<section class="vendor-detail-hero"><div class="container"><?php wz_breadcrumbs([['Vendors','vendors.php'],[$v['category'],'vendors.php?category='.urlencode($v['category'])],[$v['name'],null]]);?><div class="vendor-gallery reveal"><figure><img src="<?=h($images[0])?>" alt="<?=h($v['name'])?> portfolio"></figure><figure><img src="<?=h($images[1])?>" alt="<?=h($v['name'])?> portfolio"></figure><figure class="vendor-gallery-more"><img src="<?=h($images[2])?>" alt="<?=h($v['name'])?> portfolio"></figure></div></div></section>
<section class="section-sm"><div class="container vendor-profile-grid"><div>
  <div class="vendor-title-row reveal"><div><span class="eyebrow"><?=h($v['category'])?> · <?=h($v['city'])?></span><h1><?=h($v['name'])?></h1><p><?=h($v['locality'])?>, <?=h($v['city'])?> · <?=!empty($v['verified'])?'✓ Verified business':''?></p></div><div class="rating-pill">★ <?=h((string)$v['rating'])?> · <?=h((string)$v['reviews'])?> reviews</div></div>
  <nav class="profile-tabs"><a href="#about">About</a><a href="#services">Services</a><a href="#details">Details</a><a href="#portfolio">Portfolio</a></nav>
  <div class="profile-block reveal" id="about"><span class="eyebrow">ABOUT</span><h2>A little about <?=h($v['name'])?></h2><p><?=h($v['about'])?></p></div>
  <div class="profile-block reveal" id="services"><span class="eyebrow">WHAT THEY DO</span><h2>Services</h2><div class="service-chips"><?php foreach($v['services']??[] as $s):?><span><?=h($s)?></span><?php endforeach;?></div></div>
  <div class="profile-block reveal" id="details"><span class="eyebrow">GOOD TO KNOW</span><h2>Before you enquire</h2><div class="facts-grid"><div class="fact-card"><span>Capacity / team</span><strong><?=h($v['capacity']??'Ask vendor')?></strong></div><div class="fact-card"><span>Experience</span><strong><?=h($v['experience']??'Ask vendor')?></strong></div><div class="fact-card"><span>Policy</span><strong><?=h($v['policy']??'Ask vendor')?></strong></div></div></div>
  <div class="profile-block reveal" id="portfolio"><span class="eyebrow">PORTFOLIO</span><h2>Selected work</h2><div class="story-gallery"><?php foreach($images as $im):?><figure><img src="<?=h($im)?>" alt="<?=h($v['name'])?> work" loading="lazy"></figure><?php endforeach;?></div></div>
</div><aside class="enquiry-card reveal delay-1"><small>STARTING PRICE</small><h3><?=h($v['price'])?></h3><div class="enquiry-price"><?=h($v['tag'])?></div><form class="form-stack" data-async action="api/lead.php" method="post"><input type="hidden" name="type" value="vendor-enquiry"><input type="hidden" name="vendor" value="<?=h($v['name'])?>"><input class="hp-field" name="company_website" tabindex="-1" autocomplete="off"><div class="field"><label>Your name</label><input name="name" required></div><div class="field"><label>Phone / WhatsApp</label><input name="phone" inputmode="tel" required></div><div class="form-row"><div class="field"><label>Event city</label><input name="city" value="<?=h($v['city'])?>"></div><div class="field"><label>Event date</label><input type="date" name="event_date"></div></div><div class="field"><label>Tell them a little</label><textarea name="message" placeholder="Event type, guest count, function details and what you love about their work…"></textarea></div><button class="pill-btn wine wide" type="submit">Request pricing & availability ↗</button><button class="pill-btn outline wide heart-btn-static" type="button" data-shortlist="<?=h($v['id'])?>">♡ Save to shortlist</button><div class="success-box"></div><p class="form-note">Demo enquiries are saved locally to <code>storage/leads.csv</code>. Connect your CRM/email before production launch.</p></form></aside></div></section>
<section class="section paper-2"><div class="container"><div class="section-head"><div><span class="eyebrow">YOU MAY ALSO LIKE</span><h2>Keep comparing.</h2></div><a class="text-link" href="vendors.php?category=<?=urlencode($v['category'])?>">More <?=h($v['category'])?> ↗</a></div><div class="vendor-grid"><?php $n=0;foreach(wz_data('vendors') as $x){if($x['id']!==$v['id']&&$x['category']===$v['category']){wz_vendor_card($x);if(++$n===3)break;}}?></div></div></section>
</main><?php require __DIR__.'/includes/footer.php';?>
